{{- $fullName := include "app.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-celery
  labels:

    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "app.chart" . }}
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:

      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:

        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: celery
          image: "{{ .Values.celery.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
          env:
            - name: DD_CELERY_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-{{ .Values.celery.broker }}
                  key: {{ .Values.celery.broker }}-password
            - name: DD_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-{{ .Values.database }}
                  key: {{ .Values.database }}-password
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
      {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
