{{- if .Values.createSecret -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "app.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
{{- end }}
