apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: app
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mazharul.social@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mazharul.social@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
